name: kid_cipher_poc
description: KinID Encryption PoC for Android, iOS, and Web
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  pointycastle: ^3.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true